name: testing

on:
    pull_request:
        branches:
            - master
        types: [ opened, synchronize, reopened ]

jobs:
    mocha:
        runs-on: ubuntu-24.04
        steps:
            -   name: Checkout
                uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
            -   name: Set up PNPM package manager
                uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
            -   name: Set up NodeJS
                uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
                with:
                    node-version: 22
                    cache: pnpm
            -   name: Install dependencies
                run: pnpm install
            -   name: Mocha
                run: pnpm test
            -   name: Upload coverage
                if: success()
                uses: actions/upload-artifact@ff15f0306b3f739f7b6fd43fb5d26cd321bd4de5 # v3
                with:
                    name: coverage
                    path: |
                        coverage/
                        !coverage/tmp